"""add_gcal_sync_fields

Revision ID: 9d85b51412c9
Revises: f1a2b3c4d5e6
Create Date: 2026-04-02 19:19:40.915265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d85b51412c9'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('google_event_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_events_google_event_id'), 'events', ['google_event_id'], unique=True)
    op.add_column('users', sa.Column('google_refresh_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_calendar_connected', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_calendar_connected')
    op.drop_column('users', 'google_refresh_token')
    op.drop_index(op.f('ix_events_google_event_id'), table_name='events')
    op.drop_column('events', 'google_event_id')
    # ### end Alembic commands ###
