"""Initial schema - 21 tables

Revision ID: b80492053ef7
Revises: 
Create Date: 2026-03-12 21:09:26.890210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b80492053ef7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sota_items',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sota_items_published_at', 'sota_items', ['published_at'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('admin', 'professor', 'student', 'external', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'pending', name='userstatus'), nullable=False),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('major_field', sa.String(length=100), nullable=True),
    sa.Column('interest_fields', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('company', sa.String(length=150), nullable=True),
    sa.Column('google_subject', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_subject')
    )
    op.create_table('advisor_relations',
    sa.Column('professor_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('professor_id', 'student_id')
    )
    op.create_table('attachments',
    sa.Column('owner_type', sa.Enum('daily_block', 'task', 'report_snapshot', 'project', 'event', name='attachmentownertype'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('storage_kind', sa.String(length=50), nullable=True),
    sa.Column('preview_status', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attachments_created_by', 'attachments', ['created_by'], unique=False)
    op.create_index('ix_attachments_owner_type_owner_id', 'attachments', ['owner_type', 'owner_id'], unique=False)
    op.create_table('attendance',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.Enum('daily', 'weekly', name='attendancetype'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('check_out >= check_in', name='ck_attendance_check_out_gte_check_in'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', 'type')
    )
    op.create_index('ix_attendance_date', 'attendance', ['date'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action_type', 'audit_logs', ['action_type'], unique=False)
    op.create_index('ix_audit_logs_actor_id', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_target_type_target_id', 'audit_logs', ['target_type', 'target_id'], unique=False)
    op.create_table('daily_logs',
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('raw_content', sa.String(), server_default='', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_id', 'date')
    )
    op.create_index('ix_daily_logs_date', 'daily_logs', ['date'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('task_assigned', 'task_updated', 'daily_comment', 'daily_issue', 'attendance_missing', 'event_reminder', 'report_published', 'sota_assigned', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('delivery_channels', postgresql.JSONB(astext_type=sa.Text()), server_default='["in_app"]', nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_id_is_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'completed', name='projectstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_snapshots',
    sa.Column('report_type', sa.Enum('weekly', 'project_summary', 'advisor_summary', 'student_summary', 'tag_summary', 'organization_summary', name='reporttype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('scope_type', sa.Enum('organization', 'project', 'professor', 'student', 'tag', name='reportscopetype'), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_report_snapshots_period_end', 'report_snapshots', ['period_end'], unique=False)
    op.create_index('ix_report_snapshots_period_start', 'report_snapshots', ['period_start'], unique=False)
    op.create_index('ix_report_snapshots_report_type', 'report_snapshots', ['report_type'], unique=False)
    op.create_index('ix_report_snapshots_scope_type_scope_id', 'report_snapshots', ['scope_type', 'scope_id'], unique=False)
    op.create_table('sota_assignments',
    sa.Column('sota_item_id', sa.UUID(), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('recommended', 'assigned', 'in_review', 'submitted', 'approved', 'rejected', name='sotaassignmentstatus'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sota_item_id'], ['sota_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sota_assignments_assignee_id', 'sota_assignments', ['assignee_id'], unique=False)
    op.create_index('ix_sota_assignments_due_date', 'sota_assignments', ['due_date'], unique=False)
    op.create_index('ix_sota_assignments_status', 'sota_assignments', ['status'], unique=False)
    op.create_table('daily_blocks',
    sa.Column('daily_log_id', sa.UUID(), nullable=False),
    sa.Column('block_order', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('section', sa.Enum('yesterday', 'today', 'issue', 'misc', name='blocksection'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('visibility', sa.Enum('private', 'advisor', 'internal', 'project', name='blockvisibility'), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("visibility != 'project' OR project_id IS NOT NULL", name='ck_daily_blocks_visibility_project'),
    sa.ForeignKeyConstraint(['daily_log_id'], ['daily_logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('daily_log_id', 'block_order')
    )
    op.create_index('ix_daily_blocks_project_id', 'daily_blocks', ['project_id'], unique=False)
    op.create_index('ix_daily_blocks_search_vector', 'daily_blocks', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_daily_blocks_section', 'daily_blocks', ['section'], unique=False)
    op.create_index('ix_daily_blocks_visibility', 'daily_blocks', ['visibility'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_role', sa.Enum('viewer', 'member', 'manager', 'lead', name='projectmemberrole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id')
    )
    op.create_table('sota_reviews',
    sa.Column('sota_assignment_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sota_assignment_id'], ['sota_assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sota_reviews_reviewer_id', 'sota_reviews', ['reviewer_id'], unique=False)
    op.create_index('ix_sota_reviews_sota_assignment_id', 'sota_reviews', ['sota_assignment_id'], unique=False)
    op.create_table('tags',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('scope_type', sa.Enum('global', 'project', name='tagscopetype'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("(scope_type = 'global' AND project_id IS NULL) OR (scope_type = 'project' AND project_id IS NOT NULL)", name='ck_tags_scope_project'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_type', 'project_id', 'name')
    )
    op.create_index('ix_tags_project_id', 'tags', ['project_id'], unique=False)
    op.create_table('tasks',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('todo', 'in_progress', 'blocked', 'review', 'done', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='taskpriority'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_due_date', 'tasks', ['due_date'], unique=False)
    op.create_index('ix_tasks_priority', 'tasks', ['priority'], unique=False)
    op.create_index('ix_tasks_project_id', 'tasks', ['project_id'], unique=False)
    op.create_index('ix_tasks_project_id_status', 'tasks', ['project_id', 'status'], unique=False)
    op.create_table('comments',
    sa.Column('daily_block_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['daily_block_id'], ['daily_blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comments_author_id', 'comments', ['author_id'], unique=False)
    op.create_index('ix_comments_created_at', 'comments', ['created_at'], unique=False)
    op.create_index('ix_comments_daily_block_id', 'comments', ['daily_block_id'], unique=False)
    op.create_table('daily_block_tags',
    sa.Column('daily_block_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['daily_block_id'], ['daily_blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('daily_block_id', 'tag_id')
    )
    op.create_index('ix_daily_block_tags_tag_id', 'daily_block_tags', ['tag_id'], unique=False)
    op.create_table('events',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('event_type', sa.Enum('class', 'meeting', 'deadline', 'presentation', 'leave', 'admin', 'personal', 'project', 'sota', name='eventtype'), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('visibility', sa.Enum('private', 'advisor', 'internal', 'project', name='blockvisibility'), nullable=False),
    sa.Column('source', sa.Enum('manual', 'task', 'google_calendar', name='eventsource'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_at >= start_at', name='ck_events_end_gte_start'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_creator_id', 'events', ['creator_id'], unique=False)
    op.create_index('ix_events_end_at', 'events', ['end_at'], unique=False)
    op.create_index('ix_events_event_type', 'events', ['event_type'], unique=False)
    op.create_index('ix_events_project_id', 'events', ['project_id'], unique=False)
    op.create_index('ix_events_start_at', 'events', ['start_at'], unique=False)
    op.create_index('ix_events_task_id', 'events', ['task_id'], unique=False)
    op.create_index('ix_events_visibility', 'events', ['visibility'], unique=False)
    op.create_table('task_assignees',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'user_id')
    )
    op.create_index('ix_task_assignees_task_id_is_primary', 'task_assignees', ['task_id', 'is_primary'], unique=False)
    op.create_index('ix_task_assignees_user_id', 'task_assignees', ['user_id'], unique=False)
    op.create_table('event_participants',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('participant_role', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id')
    )
    op.create_index('ix_event_participants_user_id', 'event_participants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_participants_user_id', table_name='event_participants')
    op.drop_table('event_participants')
    op.drop_index('ix_task_assignees_user_id', table_name='task_assignees')
    op.drop_index('ix_task_assignees_task_id_is_primary', table_name='task_assignees')
    op.drop_table('task_assignees')
    op.drop_index('ix_events_visibility', table_name='events')
    op.drop_index('ix_events_task_id', table_name='events')
    op.drop_index('ix_events_start_at', table_name='events')
    op.drop_index('ix_events_project_id', table_name='events')
    op.drop_index('ix_events_event_type', table_name='events')
    op.drop_index('ix_events_end_at', table_name='events')
    op.drop_index('ix_events_creator_id', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_daily_block_tags_tag_id', table_name='daily_block_tags')
    op.drop_table('daily_block_tags')
    op.drop_index('ix_comments_daily_block_id', table_name='comments')
    op.drop_index('ix_comments_created_at', table_name='comments')
    op.drop_index('ix_comments_author_id', table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_tasks_project_id_status', table_name='tasks')
    op.drop_index('ix_tasks_project_id', table_name='tasks')
    op.drop_index('ix_tasks_priority', table_name='tasks')
    op.drop_index('ix_tasks_due_date', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_tags_project_id', table_name='tags')
    op.drop_table('tags')
    op.drop_index('ix_sota_reviews_sota_assignment_id', table_name='sota_reviews')
    op.drop_index('ix_sota_reviews_reviewer_id', table_name='sota_reviews')
    op.drop_table('sota_reviews')
    op.drop_table('project_members')
    op.drop_index('ix_daily_blocks_visibility', table_name='daily_blocks')
    op.drop_index('ix_daily_blocks_section', table_name='daily_blocks')
    op.drop_index('ix_daily_blocks_search_vector', table_name='daily_blocks', postgresql_using='gin')
    op.drop_index('ix_daily_blocks_project_id', table_name='daily_blocks')
    op.drop_table('daily_blocks')
    op.drop_index('ix_sota_assignments_status', table_name='sota_assignments')
    op.drop_index('ix_sota_assignments_due_date', table_name='sota_assignments')
    op.drop_index('ix_sota_assignments_assignee_id', table_name='sota_assignments')
    op.drop_table('sota_assignments')
    op.drop_index('ix_report_snapshots_scope_type_scope_id', table_name='report_snapshots')
    op.drop_index('ix_report_snapshots_report_type', table_name='report_snapshots')
    op.drop_index('ix_report_snapshots_period_start', table_name='report_snapshots')
    op.drop_index('ix_report_snapshots_period_end', table_name='report_snapshots')
    op.drop_table('report_snapshots')
    op.drop_table('projects')
    op.drop_index('ix_notifications_user_id_is_read', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_daily_logs_date', table_name='daily_logs')
    op.drop_table('daily_logs')
    op.drop_index('ix_audit_logs_target_type_target_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_type', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_attendance_date', table_name='attendance')
    op.drop_table('attendance')
    op.drop_index('ix_attachments_owner_type_owner_id', table_name='attachments')
    op.drop_index('ix_attachments_created_by', table_name='attachments')
    op.drop_table('attachments')
    op.drop_table('advisor_relations')
    op.drop_table('users')
    op.drop_index('ix_sota_items_published_at', table_name='sota_items')
    op.drop_table('sota_items')
    # ### end Alembic commands ###
